# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Sunny's Blog
subtitle: ''
description: 千里之行，始于足下
keywords:
author: Sunny
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://codersunny.com
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md # 部署的时候不包含的文件

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false #是否启用资源文件夹（用来存放相对路径图片或文件）
relative_link: false # 把链接改为与根目录的相对位址
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true #自动判断代码语言
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD # 博客日期格式
time_format: HH:mm:ss # 博客时间格式
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

#归档页的分页设置
archive_generator: #归档页的配置
  per_page: 30 #归档页每页博客数
  yearly: true #按年归档
  monthly: true #按月归档
  
  #标签页的分页设置
tag_generator:
  per_page: 20 #标签页每页博客数

# 主题相关
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly #butterfly

  # 设置博客单词统计
symbols_count_time:
  symbols: true  # 文章字数统计
  time: true  # 文章阅读时间统计
  total_symbols: true  # 站点总字数统计
  total_time: true # 站点总阅读时间统计
  exclude_codeblock: false

# 搜索
search:
    path: search.xml
    field: post
    format: html
    limit: 10000

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:HappyCoderSunny/HappyCoderSunny.github.io.git
  branch: master
  
# 音频播放器相关
aplayer:
  meting: true
  asset_inject: false
  
# 看板娘相关配置
live2d:
  enable: true
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    use: live2d-widget-model-tororo # npm-module package name
    
# Algolia 搜索功能配置
algolia:
  appId: 'MY0L9JC4NK'
  apiKey: 'e5dd1288ea8d33ac5e46ef2a11c0ce56'
  adminApiKey: '0f00af9c6896a88c57483628ada52fc3'
  indexName: 'hexo_search'

# 配置数学符号显示功能
markdown:
  plugins:
    - plugin:
      name: '@neilsustc/markdown-it-katex'
      options:
        strict: false
    
    
    
    
    

  
